# This is a basic workflow to help you get started with Actions
name: norminette
on: [push, pull_request]

jobs:
  norminette_v3_job:
    runs-on: ubuntu-latest
    name: norminette v3
    steps:
    - uses: alexandregv/norminette-action@v3
